version: '3.4'

services:
  banking.api:
    image: ${DOCKER_REGISTRY-}bankingapi
    build:
      context: .
      dockerfile: Banking.Api/Dockerfile



  transfer.api:
    image: ${DOCKER_REGISTRY-}transferapi
    build:
      context: .
      dockerfile: Transfer.Api/Dockerfile


  mvcwebapp:
    image: ${DOCKER_REGISTRY-}mvcwebapp
    build:
      context: .
      dockerfile: MvcWebApp/Dockerfile

