version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  ms-sql-server:
    container_name:  ms-sql-server
    image: mcr.microsoft.com/mssql/server 
    ports:
       - "1433:1433"
    environment:
      SA_PASSWORD: "Titan#12"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      MSSQL_TCP_PORT: "1433"

  banking.api:
    container_name: bankingapi
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:BankingDbConnection=Server=ms-sql-server,1433;Database=Banking.DB;User Id=SA;Password=Titan#12"
      - "EventBus:HostName=rabbitmq"
      #- ASPNETCORE_URLS=https://+:443;http://+:80

    depends_on:
       - ms-sql-server
       - rabbitmq
    ports:
      - "8000:80"

    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  
  transfer.api:
    container_name: transferapi
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:TransferDbConnection=Server=ms-sql-server,1433;Database=Transfer.DB;User Id=SA;Password=Titan#12"
      - "EventBus:HostName=rabbitmq"
      #- ASPNETCORE_URLS=https://+:443;http://+:80

    depends_on:
       - ms-sql-server
       - rabbitmq

    ports:
      - "8001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  mvcwebapp:
    container_name: mvcwebapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8002:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
